### ISSUE TITLE
Tapicero can't create databases with couchdb 1.6

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-platform#102]
When a user is created on a machine with couchdb 1.6, tapicero breaks and can't create the database for that user.

We need to find out why and fix this.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.
I'll close this issue for now, it might be reopened in the future if it makes sense.

**Comment by varac** [comment]
i'd like to re-open this again, as stated in the gdoc: "it's blocking an important issue for our goal". I'd like to stabilize the platform side of things and couch 1.6 would possibly help here a lot over using bigcouch (which is based on couch 1.1).

**Comment by bwagnerr** [comment]
I agree, is there any issue in LEAP for that? How should we go about this?

**Comment by varac** [comment]
let's reopen this issue and talk tomorrow about this.
There's no upstream issue, because leap is still using bigcouch so we need to take care of this ourselves. @bwagnerr you said you could have a look into this ?

**Comment by varac** [comment]
i propose that we should close this issue because we'll implement the creation of user-db into soledad-server (#104)
