### ISSUE TITLE
Try couchdb 1.6 on unstable.pix

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#103]
What
============
We would like to use couch 1.6.
Our first step will be use couch 1.6 manually on unstable.pix.

Definition of done:
==============
Create 2 accounts and see them working on unstable without bigcouch. features: (sending, receiving, soledad syncing, key exchange)

Before, varac was commented " blocked by #102 "

**Comment by shyba** [comment]
Unblocked by #104 
Tapicero is dead on that branch. It should be possible to do this card now as suggested by @bwagnerr

**Comment by shyba** [comment]
unstable is running on couch 1.6
So far everything worked

**Comment by bwagnerr** [comment]
Worked like a charm for me too! I'll close this
