### ISSUE TITLE
Soledad should be able to create users db

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-platform#104]
It is currently being created by Tapicero (with some bugs on couch 1.6).
As discussed on #leap, this should be done on Soledad after successfully user authentication.

Definition of done:
=============
Without Tapicero, I can register myself and sync Soledad without errors.

Steps
- [x] add a test for that
**
- [x] implement
** This was already a feature before, I just reverted the changes to disable it and removed monkey patches on tests to also test db creation. PR 279
- [ ] check required privilege within puppet scripts (we need to be able to create databases)
- [ ] check locally if platform works well without tapicero

Also (just to keep track)
- [x] help merging PR 257 on Soledad -- merged
- [ ] help merging PR 279 on Soledad

Related (should also help) https://github.com/pixelated/project-issues/issues/135

**Comment by varac** [comment]
i like this approach, would be great to implement this.

**Comment by shyba** [comment]
https://github.com/leapcode/soledad/pull/263

**Comment by shyba** [comment]
@varac can you help me with this step?
- [ ] - check required privilege within puppet scripts (we need to be able to create databases)
I am still kind of lost looking for where this is set. Soledad user needs to be admin now.

**Comment by varac** [comment]
i created a [related issue in LEAPs bugtracker](https://leap.se/code/issues/7416)

**Comment by varac** [comment]
here's the pull req for leap_platform that allows soledad-server to run with admin privs: https://github.com/pixelated/leap_platform/pull/1

**Comment by shyba** [comment]
We (leap+pixelated) are discussing security on possible alternatives.
All of them are easy to implement, but hide some side effects.

**Comment by varac** [comment]
@shyba i created a script on unstable.pix, `/usr/local/bin/couch_create_db.sh`.
soledad-server should call it with:

```
sudo -u soledad-admin couch_create_db.sh <DBNAME>
```

calling it without sudo will fail, as expected:

```
root@unstable1:~# sudo -u soledad-admin couch_create_db.sh test_3

root@unstable1:~# sudo -u soledad couch_create_db.sh test_4
Error - "/usr/bin/curl -s --netrc-file /etc/couchdb/couchdb.netrc -X PUT http://127.0.0.1:5984/test4" did not succeed, this was the return code:
{"error":"unauthorized","reason":"You are not a server admin."}
```

i'll polish this script a bit, but it works for now. Could you care for the soled-server integration pls ?

**Comment by varac** [comment]
things i have done in order to get the script working as soledad-admin user that need to get integrated:

[ ] create soledad-admin (system-)user and group
[ ] chmod 640 /etc/couchdb/couchdb-admin.netrc
[ ] chown bigcouch:soledad-admin /etc/couchdb/couchdb-admin.netrc
[ ] configure /etc/sudoers.d/soledad_admin, mode 0440
[ ] uncomment "includedir /etc/sudoers.d" in /etc/sudoers

**Comment by bwagnerr** [comment]
@varac looks good, the only thing is that the database usernames follow the pattern "user-hexstringUUID" so that regex has to be adapted I think

**Comment by shyba** [comment]
@varac check https://github.com/varac/soledad/pull/1
I will deploy this to wazokazi tomorrow and check how it behaves.

**Comment by varac** [comment]
@shyba why deploy to wazokazi and not unstable.pix ? in my understanding, if we actively develop on any env, it should be unstable, and wazokazi will be deployed when it's ready for production ?

**Comment by shyba** [comment]
Because it was late and I was dizzy. :P
It is unstable. Lol
Em 16/09/2015 06:31, "varac" <notifications@github.com> escreveu:

**Comment by shyba** [comment]
https://github.com/leapcode/soledad/pull/279 -- soledad server side done
Installing it on unstable and killing tapicero there to see what happens.

**Comment by shyba** [comment]
Unstable is running on our branch.
I had to fix an issue on the client side as well, but as far as I could test it is working now.
I stopped tapicero and changed pixelated to use this branch for soledad.client, created a brand new accound and accessed it. The db was created during first sync.
Discoveries (**none of them are blockers**):
-- soledad-admin will have to install soledad package as well. The script is inside the package and can't be run without the code.
-- soledad was unable to access config file (my fault), but didn't throw any errors. EACCESS isn't raised on config reader, it just read default values and go ahead. Maybe bug?

**Comment by varac** [comment]
@shyba what do you mean with this, i don't understand:
 
`-- soledad-admin will have to install soledad package as well. The script is inside the package and can't be run without the code.` 

regarding the config reader, this is unfortnuate, but i think it's not a blocker for us.

**Comment by shyba** [comment]
It is about the sudo idea, the soledad user has soledad installed,
soledad-admin user will need it too, but I don't think it is a problem.
Anyway, we need to check the scripts that will implement your sudo idea. I
don't get it yet.
I think it is easier to explain live. :P
Ping me when you're around.

2015-09-23 8:48 GMT-03:00 varac <notifications@github.com>:

> @shyba <https://github.com/shyba> what do you mean with this, i don't
> understand:
>
> -- soledad-admin will have to install soledad package as well. The script
> is inside the package and can't be run without the code.
>
> regarding the config reader, this is unfortnuate, but i think it's not a
> blocker for us.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated/pixelated-platform/issues/104#issuecomment-142576629>
> .
>



-- 
Victor Shyba

**Comment by shyba** [comment]
Merged. Soledad side is done, @varac is finishing platform side.
Em 23/09/2015 09:56, "Victor Shyba" <victor.shyba@gmail.com> escreveu:
