### ISSUE TITLE
Create Howto for vagrant setup 

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#106]
both for running bigcouch and couch1.6

**Comment by varac** [comment]
ok, waiting for micah to review https://gitlab.com/leap/platform/merge_requests/69.
after that, a simple "vagrant up" will bring up a one-node platform (i'll work on the documentation now).

**Comment by varac** [comment]
i pushed to our [pixelated-platform-environments repo](https://github.com/pixelated/project-issues/wiki/platform-enviroments#platform-configuration-environments), please review the README.md and QA.

**Comment by kaeff** [comment]
Having when following the tutorial: `vagrant plugin install sahara` fails

```
➜  pixelated-project.org git:(master) ✗ be leap local start local1
 = installing vagrant plugin 'sahara'
 = run vagrant plugin install sahara 2>&1
   - FAILED (exit 1) Installing the 'sahara' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.
 = bailing out
```

**Comment by kaeff** [comment]
my bad, seems to be related to my machine's vagrant / ruby setup..

**Comment by kaeff** [comment]
I succeeded installing sahara after installing leap_cli from source and upgrading to vagrant 1.7.4.

To install leap_cli,  run the following commands in the cloned repo:
```
gem install bundler
bundle install
gem build leap_cli.gemspec
gem install leap_cli
```

**Comment by kaeff** [comment]
Local deploy worked, but I had to change file permissions on the `vagrant.key` shipped with the leap_cli gem.

**Comment by varac** [comment]
the above vagrant issue is fixed in latest leap_platform. please make sure to update the submodules in the with `git submodule update` !

**Comment by kaeff** [comment]
QA'ed :+1:
