### ISSUE TITLE
Integrate Pixelated tests into leap_cli and nagios

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#109]
we decided yesterday that we should integrate pixleated specific tests into leap_cli and nagios
i.e. 

- [x] parse docker logs for errors
- [x] monitor docker
- [ ] functional test like create account, login, logout, etc.

**Comment by bwagnerr** [comment]
This would be good, but is not really needed for wazokazi so I'm dropping the label

**Comment by kaeff** [comment]
@fbernitt suggested limiting this to a functional test that logs into the default accounts on try

**Comment by cz8s** [comment]
we already monitor the user-agent logs and add them to nagios.
I think thats meant with 'parse docker logs for errors'

**Comment by cz8s** [comment]
tgo

**Comment by cz8s** [comment]
added check to see if docker is running:
pixelated/puppet-pixelated@b3ae63dad1d9234c70305a4e8acac44de02c6100

**Comment by cz8s** [comment]
and more tests:
pixelated/pixelated-puppet@87b62aa56e17618d7631880a0ef9cec188f26704

**Comment by cz8s** [comment]
waiting for #142

**Comment by cz8s** [comment]
See PR in https://github.com/leapcode/leap_platform/pull/92

**Comment by bwagnerr** [comment]
On deploying unstable and dev yesterday, I saw Pixelated specific tests for the daemons and the dispatcher, they worked nicely, so i'll close this one
