### ISSUE TITLE
add checks for the user-agent logs to nagios

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-platform#111]
we want to know if any user-agent has problems.
the best way is to monitor the logs and display errors on nagios.

**Comment by varac** [comment]
see site_check_mk/manifests/agent/tapicero.pp in leap_platform how we do this for i.e. tapicero

**Comment by cz8s** [comment]
basic checks are in pixelated-platform/modules/pixelated/files/check_mk/user-agent.cfg
we can add more there, but basically it works. seen nagios complain :)

**Comment by cz8s** [comment]
see 17ae6609ae603359a256d8eecb874f6afcd26db3 and d6522a82efeb072a161748791085673264872e66

**Comment by kaeff** [comment]
showcased in the weekly
