### ISSUE TITLE
leap deploy kills docker

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-platform#112]
on every 'leap deploy' docker gets stopped and puppet fails to restart it.

**Comment by shyba** [comment]
Hey Christoph,

Would you mind to paste the failure from puppet? Or are there no logs after?
It is just a matter of better context for the card.

2015-09-18 15:34 GMT-03:00 Christoph <notifications@github.com>:

> on every 'leap deploy' docker gets stopped and puppet fails to restart it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated/pixelated-platform/issues/112>.
>



-- 
Victor Shyba

**Comment by cz8s** [comment]
'''
err: /Stage[main]/Pixelated::Dispatcher/Service[docker]: Failed to call refresh: Could not start Service[docker]: Execution of '/etc/init.d/docker start' returned 1:  at /srv/leap/files/puppet/modules/pixelated/manifests/dispatcher.pp:16
'''

**Comment by varac** [comment]
i added the wazokazi label because at least for me this is reproducible on *every* deploy and will just brutally shutdown docker and therefore all running useragents on every deploy.

**Comment by cz8s** [comment]
should go through qa before closing

**Comment by varac** [comment]
damn, i just got this on `leap deploy unstable1`: 
```
err: /Stage[main]/Pixelated::Dispatcher/Service[docker]: Failed to call refresh: Could not start Service[docker]
```
i used the latest pixelated-platform-environments and made sure the about fix is present in my pixelated-platform submodule :/

**Comment by cz8s** [comment]
docker restart exists with 1 if a image was running.
need to patch the init script ...

**Comment by cz8s** [comment]
done in commit pixelated/pixelated-platform@639d7d20d419408dd2c8a521169921ecfe48d60b

**Comment by bwagnerr** [comment]
It worked 3 times for me on Friday and another now, I would consider this done

**Comment by giovaneliberato** [comment]
Yes, it works
My UA is now on version pixelated/pixelated-platform@2981e33

**Comment by giovaneliberato** [comment]
@re-nobre found an inconsistency on this. She was logged on wazokazi.is:8080 it wasn't on the latest version.. is that an expected issue? @varac @cz8s

**Comment by cz8s** [comment]
No. It shouldn't happen

**Comment by giovaneliberato** [comment]
@cz8s just realized that I commented on the wrong issue.. this was about pixelated/project-issues/issues/161

**Comment by cz8s** [comment]
Oh, comment in the wrong ticket?

**Comment by giovaneliberato** [comment]
Yes. Two times 

![](https://s3.amazonaws.com/img.gawkerassets.com/img/17ladkk6lexvnjpg/original.jpg)
