### ISSUE TITLE
[leap] Configure soledad-server create-user-db script to access couchdb with admin rights

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#114]
see https://leap.se/code/issues/7502 for details

**Comment by varac** [comment]
follow up to #104

**Comment by pereiragislene** [comment]
Netrc file for create-user-db is now configurable. See [PR 280](https://github.com/leapcode/soledad/pull/280).

**Comment by varac** [comment]
blocked by #115

**Comment by varac** [comment]
@cz8s and me paired on this today, it is deployed on unstable and works from what we can tell.

**Comment by cz8s** [comment]
works on staging
