### ISSUE TITLE
Nagios should not complain about docker interface

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#118]
nagios sometimes complains about the interface speed of docker0:

```
root@unstable1:~# ncli_unstable
Interface 2          CRITICAL CRIT - [docker0] (down)(!!) speed unknown, in: 0.00B/s, out: 0.00B/s
```

**Comment by re-nobre** [comment]
Hey @varac! Is it still happening?
If not, can we close it?

**Comment by varac** [comment]
It happens from time to time, but i think we can ignore it because we're moving away from docker anyway soon.

**Comment by bwagnerr** [comment]
I'll close it then! thanks for the info
