### ISSUE TITLE
[leap] Remove tapicero couchdb user

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#119]
see https://leap.se/code/issues/7514

**Comment by varac** [comment]
the smartest way would be to implement deleting docs in `/usr/local/bin/couch-doc-update`, and calling this from leap_platform. 
`/usr/local/bin/couch-doc-update` is deployed by leap_platform using the couchdb submodule.

**Comment by kaeff** [comment]
Like `couch-doc-update ---delete --db _users --id org.couchdb.users:tapicero` 

`couch-doc-update` is a bit like tapicero: Mostly boilerplate around couchrest. I'm a bit worried we're giving it too much responsibility with this approach, but I'll spike the above pseudocode.

**Comment by kaeff** [comment]
Unfortunately, this requires some orchestrations of pull requests & submodule updates since the script is included from `puppet_couchdb`.

I've pushed the changes in branches (`couch-doc-update-delete` in both repos), but so far only opened the PR for the submodule.

@varac, would you take it from here? Thanks!

**Comment by varac** [comment]
there are two merge requests pending: https://gitlab.com/leap/couchdb/merge_requests/2 and https://gitlab.com/leap/platform/merge_requests/78, this should be QAed after these are merged.

It could be QAed by deploying the merged platform changed to wazokazi.is, and after this leap test should not complain about additional couch users like this:

```
--- pixelated-platform-environments/wazokazi.is ‹master* M› » leap test
 = [pixelated.wazokazi.is] PASS: Network > Can connect to internet?
 = [pixelated.wazokazi.is] PASS: Network > Is stunnel running?
 = [pixelated.wazokazi.is] PASS: Network > Is shorewall running?
 = [pixelated.wazokazi.is] PASS: CouchDB > Are daemons running?
 = [pixelated.wazokazi.is] PASS: CouchDB > Is CouchDB running?
 = [pixelated.wazokazi.is] PASS: CouchDB > Is cluster membership ok?
 = [pixelated.wazokazi.is] PASS: CouchDB > Are configured nodes online?
 = [pixelated.wazokazi.is] FAIL: CouchDB > Do ACL users exist? [couchdb.rb:74]:
 = [pixelated.wazokazi.is]   Expected: 6
 = [pixelated.wazokazi.is]     Actual: 7
 = [pixelated.wazokazi.is] Tests halted on failure (because of --no-continue).
 = bailing out 
```

**Comment by kaeff** [comment]
Although https://gitlab.com/leap/couchdb/merge_requests/2 says different, all PRs are merged. The according test (*Do ACL users exist?*) finishes successfully.

Can be launched IMHO.
