### ISSUE TITLE
[leap] New soledad-server causes soledad-sync platform tests to fail

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#123]
please see https://leap.se/code/issues/7523 for details, and comment on the leap issue

**Comment by shyba** [comment]
Reflecting my comment on LEAP issue here:
```
As you can see on Soledad[0], the first request from a new user can raise DatabaseDoesNotExists.
This is also true on original u1db implementation[1].

The database creation happens during a POST on a real, authenticated sync. Following u1db implementation.

This test fails because it tries a GET request. [2]

I think Soledad is ok with that, but we can change to make this test pass, although I don't feel comfortable changing this default implementation of u1db protocol. Other solution would be to POST instead of GET, but that will require a lot more on request body in order to pass all the request format checks that otherwise will throw a BadRequest exception.
What is the original purpose of this test? If it is to ensure that a new user is able to get a new database, I would call 'sudo -u soledad-admin create-user-db user-{hash}' to check if everything went fine.
Also, may I ask why is this a Webapp test? 'Can sync soledad' sounds like a Soledad test.

Feel free to ping me back. :)

[0] - https://github.com/pixelated/soledad/blob/develop/client/src/leap/soledad/client/sync.py#L77
[1] - https://bazaar.launchpad.net/~ubuntuone-control-tower/u1db/trunk/view/head:/u1db/sync.py#L102
```

**Comment by re-nobre** [comment]
Hey,@varac! I'm looking in this issue and I'm confused. For me, it's a discussion not a thing to develop.

Is there any thing that we (Pixelated team) can develop related to it?

**Comment by varac** [comment]
currently, kali from LEAP is working on this.

**Comment by varac** [comment]
i'm currently working with kali on this.

**Comment by varac** [comment]
waiting for meskio and kali to review and update https://github.com/leapcode/leap_platform/pull/86

**Comment by varac** [comment]
done !

**Comment by varac** [comment]
for QA:

- merge latest leap_platform into ours
- update leap_platform submodule in pixelated-platform-environments
- deploy to unstable
- `leap test` should show a successful soledad sync test

**Comment by varac** [comment]
@giovaneliberato: please hold on QA'ing. i now remember what the problem is: 
We disabled the webapp and soledad sync test because they fail for plain couchdb (and they would succeed with bigcouch).
This is the regarding [leap issue](https://leap.se/code/issues/7625) for this. 

Until it is fixed, this is blocked and cannot get QAed.

**Comment by varac** [comment]
this is the last remaining issue for the migration to couchdb btw.
