### ISSUE TITLE
Automate couchdb 1.6 changes

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-platform#125]
This is the follow up to #103 
Description and definition of done will be discussed on tomorrow's stand up.

**Comment by varac** [comment]
@shyba: could you sum up the changes that needs to be made in leap_platform for this pls ?

**Comment by varac** [comment]
for the record, this should be enough to automate the installation *from scratch* of plain couchdb:

put this into the node definition (i.e. pixelated-project.org/nodes/unstable1.json):
```
"couch": {
    "master": true,
    "pwhash_alg": "pbkdf2"
  }
```

**Comment by varac** [comment]
see #126 for follow up issue

**Comment by varac** [comment]
ok, this works as it should. we only need to include https://github.com/pixelated/pixelated-platform/issues/125#issuecomment-151120882 into the platform builds to use it in our platform builds after QA

**Comment by re-nobre** [comment]
hey, @varac! 
Just make sure, in what environments we have couch 1.6 now?

**Comment by cz8s** [comment]
* we have couch1.6 on unstable and staging
* we have bigcouch on dev,try and wazokazi

I will deploy to try today so we will have couch on try later.

@shyba: how do we migrate wazokazi to couch?

**Comment by cz8s** [comment]
we migrated try from bigcouch to couch. we had to dump everything, install couch, and restore everything. this is what we did:

```
mkdir lib-backup
cd lib-backup/
vim split.rb
for db in $(curl -q -X GET http://127.0.0.1:5984/_all_dbs | ruby split.rb); do couchdb-dump http://admin:PASSWORD@localhost:5984/$db > $db.file; 
done
```

the split.rb looks like this:
```ruby
#!/usr/bin/ruby
require 'json'
my_hash = JSON.parse($stdin.read())
puts my_hash
```

then change the configuration to use couchdb and do a ```leap deploy``

then restore everything from the files:
```
for file in *; do  curl -X PUT http://admin:PASSWORD@localhost:5984/$(basename $file .file); couchdb-load http://admin:KWjh5bKmCQcbe6YqkUXhc_KsGptK2sLy@localhost:5984/$(basename $file .file) --input=$file; done
```

another ```leap deploy``` to fix the access rights, and you should be done(tm)

**Comment by cz8s** [comment]
only problems. dump and restore took hours. if we do this on wazokazi, it will be down for some time

**Comment by shyba** [comment]
Are we going to migrate Wazokazi on the same card?
The automation seems to work already. :+1:

**Comment by cz8s** [comment]
I think we should have a new card for that because it might take a while until we migrate wazokazi.
We have to warn our users because the migration will take some hours ...

**Comment by cz8s** [comment]
I created https://github.com/pixelated/project-issues/issues/163 for wazokazi.
This can be closed.

**Comment by varac** [comment]
Dump and restore procedure is documented here: https://leap.se/en/docs/platform/services/couchdb#rebalance-cluster

This method uses scripts already present, and are easier to use.
