### ISSUE TITLE
soledad-userdb creation should give leap-mx access to userdbs

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#127]
this is the acl of a userdb using tapicero and bigcouch:

```
root@dev1:~# curl -s --netrc-file /etc/couchdb/couchdb-leap_mx.netrc -X GET
'http://127.0.0.1:5984/user-fbfefde7441d5aba720891d556fb50e6/_security'
{"admins":{"names":["admin"],"roles":[]},"members":{"names":["soledad","leap_mx"],"roles":["replication"]}}
```

this is using couchdb and soledad-server creating userdbs:

```
root@unstable1:/etc/leap# curl -s --netrc-file /etc/couchdb/couchdb.netrc -X GET 'http://127.0.0.1:5984/user-9898ab508ff2e622cb3c897cea1f4e3a/_security'
{"admins":{"names":[],"roles":[]},"members":{"names":["soledad"],"roles":[]}}

```

**Comment by shyba** [comment]
It needs a migration script as well. The migration script should add 'leap_mx' to existing accounts.

**Comment by varac** [comment]
we should make the couchdb user configurable, as it was in tapicero. 
i.e. soledad should read the mx user from `/etc/soledad/soledad-server.conf` i.e.
```
leap_mx_couchdb_user = leap_mx
```

**Comment by varac** [comment]
i made changes to the platform that add the above config variable to `/etc/soledad/soledad-server.conf`. soledad-server just needs to pick it from there.

**Comment by varac** [comment]
i saw the changes from @vshyba to soledad from yesterday (`d22e495 - [feat] read security doc from configuration (12 hours ago) <Victor Shyba>`), and installed the soledad-server deb containing this change to unstable.

i registered a new user, but the regarding userdb was not created. 

```
root@unstable1:~# curl -s --netrc-file /etc/couchdb/couchdb.netrc -X GET 'http://127.0.0.1:5984/identities/_all_docs?include_docs=true' | grep varac102 | cut -d, -f 1
{"id":"b89f584ad19766e1f1a7fec0ab3eca94"
root@unstable1:~# curl -s --netrc-file /etc/couchdb/couchdb.netrc -X GET 'http://127.0.0.1:5984/_all_dbs' | grep b89f584ad19766e1f1a7fec0ab3eca94

```


docker logs show this:

```
root@unstable1:~# docker logs varac102
2015-10-27 09:48:37 [leap.soledad.client.api] ERROR Soledad exception when syncing!
*--- Failure #17 ---
Failure: leap.soledad.common.errors.InvalidAuthTokenError: 
*--- End of Failure #17 ---

Generating keys - this could take a while...
The key len is: 64
2015-10-27 09:54:19 [leap.soledad.client.api] ERROR Soledad exception when syncing!
*--- Failure #11 ---
Failure: leap.soledad.common.errors.InvalidAuthTokenError: 
*--- End of Failure #11 ---

2015-10-27 09:54:19 [twisted] ERROR Traceback (most recent call last):
2015-10-27 09:54:19 [twisted] ERROR Failure: leap.soledad.common.errors.InvalidAuthTokenError: 

```

**Comment by varac** [comment]
creating the userdb manually fails as well:

```
root@unstable1:/etc/leap# create-user-db user-b89f584ad19766e1f1a7fec0ab3eca94
Traceback (most recent call last):
  File "/usr/bin/create-user-db", line 60, in <module>
    security_conf=CONF['database-security'])
TypeError: open_database() got an unexpected keyword argument 'security_conf'

```

**Comment by cz8s** [comment]
I really don't know what this ticket is about. But I think it is the ticket where we track that userdbs should be created and mails from external domains should be delivered to the user via leap-mx.
So I tested it on staging:
* creating the account and logging in works
* mail from outside to the new user gets accepted
* mail from outside arrives in the inbox of the user

**Comment by cz8s** [comment]
everything works now.
We can even migrate broken accounts with ``` create-user-db --migrate-all```

**Comment by shyba** [comment]
Sorry, I totally forgot about the unmerged PR! :tomato: 
https://github.com/leapcode/soledad/pull/291

Moving to leap_pr column.

**Comment by cz8s** [comment]
But that was in #128

**Comment by cz8s** [comment]
Oh. Another PR ...
