### ISSUE TITLE
convert-to-pixelated.sh complain about use root and docker

### ISSUE THREAD

**Issue by gomex** [pixelated/pixelated-platform#134]
Following documentation[1] the installation don't works. I got this error:

```
===============================================
+ echo 'configuring leap'
configuring leap
+ echo ===============================================
===============================================
+ sudo mkdir -p /home/leap/configuration/
+ ME=root
+ sudo chown root /home/leap/configuration/
+ cd /home/leap/configuration/
+ '[' -n '' ']'
+ leap new --platform=/home/leap/leap_platform .
 = `leap` should not be run as root.
 = bailing out 
Reboot into new kernel version so that docker support is enabled 
````
I already reloaded my vagrant box and I got the same error. How can I do to provide my environment to start my test? Should I use different user?

[1] - https://github.com/pixelated/pixelated-platform/blob/master/README.md#1-set-up-your-own-pixelated-platform

**Comment by varac** [comment]
@gomex sorry, we are currently migrating everything from this repo to other repositories.
Please have a look at https://github.com/pixelated/puppet-pixelated for updated documentation. Feel free to join the irc chat in case you have more questions: https://pixelated-project.org/#contact

**Comment by gomex** [comment]
But you don't migrating the code to provide leap platform, correct?

**Comment by varac** [comment]
gomex: we dropped support for the install-everything script (convert-to-pixelated.sh).
The steps how to install the leap platform can be found here: https://github.com/pixelated/puppet-pixelated#1-creating-a-leap-provider

Besides this, we'll add a Vagrantfile that sets up pixelated and leap_platform together soon.

**Comment by gomex** [comment]
What you think about create a docker to provide this?

**Comment by varac** [comment]
@gomex Docker is a great tool, but having the pixelated dispatcher running requires quite a bunch of services (the leap_platform alone has some services/daemons as dependency).
On top of that, currently the dispatcher itself uses docker to run the useragent for each user.
So i think Vagrant is the better approach here, but if anyone likes to sit down and figure out what it needs to dockerize it all, i'd be happy to try myself (though i think this is quite some work).
If you or anyone else want to do this, ping me and i can point you to someone who already spend some time on this, but gave up afaik.

**Comment by varac** [comment]
closing this because this has been refactored and documented in this section of the puppet-pixelated README.md: https://github.com/pixelated/puppet-pixelated#2-adding-pixelated-to-your-existing-leap-configuration
