### ISSUE TITLE
ensure couchrest is not too new

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-platform#136]
the platform installs couchrest to configure couchb.
Problem is, that the lates version depends on ruby 2.0
Thats why the pixelated-platform pipeline fails at the moment. on configure-leap_with_dispatcher

**Comment by cz8s** [comment]
created leap pr: https://github.com/leapcode/puppet_couchdb/pull/4

**Comment by varac** [comment]
blocked by: https://github.com/pixelated/pixelated-platform/issues/137

**Comment by cz8s** [comment]
pipeline is green, everything merged. This can be closed
