### ISSUE TITLE
Install pnp4nagios from pixelated jessie-backport repo

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#141]
see https://leap.se/code/issues/7604 for more details

**Comment by cz8s** [comment]
we have a pnp4nagios pipeline now. It builds the package with git-buildpacke directly from the debian repo and publishes them on packages.pixelated-project.org:jessie-snapshots. thats enough for us at the moment. But in the long run, it would be nice to make pnp4nagios optional
