### ISSUE TITLE
Configure platform pipeline for jessie

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#144]

**Comment by varac** [comment]
i see the (jessie) platform pipeline still uses the leap 0.8 repository, but the [successful jessie leap ci builds](https://squirrel.leap.se:8080/job/platform_citest_jessie/lastSuccessfulBuild/) runs with the experimental-0.9 repo.
It's config is this:

```
testbot@greyhound:~/rewire_citest_jessie/rewire$ cat nodes/rewcitestjessie1.json 
{
  "ip_address": "10.5.5.81",
  "services": [
    "couchdb",
    "monitor",
    "mx",
    "soledad",
    "webapp"
  ],
  "platform": {
    "major_version": "0.9",
    "version": "0.9"
  },
  "sources": {
    "platform": {
      "apt": {
        "basic": "http://deb.leap.se/0.9"
      }
    }
  },
  "couch": {
    "master": true,
    "pwhash_alg": "pbkdf2"
  }
}

```

I didn't test with the experimental-0.8 repo.

**Comment by varac** [comment]
this is needed until we have all packages needed for jessie in the official 0.8 repo.

**Comment by cz8s** [comment]
leap_cli does not want to have a colon in its arguments:
```
leap node add somehostname source.platform.apt.basic:"http://deb.leap.se/0.9"
```
does not not work. leap strips everything after the http because of the colon

**Comment by cz8s** [comment]
Opened leap-issue: https://leap.se/code/issues/7710

**Comment by cz8s** [comment]
some package are missing on the leap side: https://leap.se/code/issues/7733

**Comment by cz8s** [comment]
@varac: so what url should I use then?

**Comment by varac** [comment]
@cz8s :

`leap node add somehostname source.platform.apt.basic:"http://deb.leap.se/experimental-0.8"`

**Comment by cz8s** [comment]
Since we have to deploy to try and staging regularly, I reverted our platform to build on wheezy during the holidays. I will continue next year.
Happy new year everyone :)

**Comment by cz8s** [comment]
waiting on #140

**Comment by varac** [comment]
platform build fails during shutdown stage on jessie after the `sudo poweroff` cmd, see http://go.dfi.local:8153/go/tab/build/detail/pixelated-platform/1080/shutdown/1/shutdown#

i can reproduce the problem:
```
root@go-agent4:~# ssh go@192.168.136.253 sudo poweroff
Connection to 192.168.136.253 closed by remote host.
root@go-agent4:~# echo $?
255
root@go-agent4:~# 
root@go-agent4:~# ssh go@192.168.136.253 sudo id 
uid=0(root) gid=0(root) groups=0(root)
root@go-agent4:~# echo $?
0
root@go-agent4:~# ssh go@192.168.136.253 sudo shutdown -h now
Connection to 192.168.136.253 closed by remote host.
root@go-agent4:~# echo $?
255

```

but i don't know why this cmd gives an error code of 255, because the VM is being powered off just fine.

**Comment by varac** [comment]
i don't get it. i appended `|| /bin/true` to ignore the exit code, however, the build still fails: http://go.dfi.local:8153/go/tab/build/detail/pixelated-platform/1081/shutdown/1/shutdown

same cmd manually does succeed:

```
root@go-agent4:~# ssh go@192.168.136.253 sudo poweroff || /bin/true
go@192.168.136.253's password: 
Connection to 192.168.136.253 closed by remote host.
root@go-agent4:~# echo $?
0

```

**Comment by varac** [comment]
aha

```
root@go-agent4:~# ssh go@192.168.136.253 'sudo poweroff || /bin/true'
go@192.168.136.253's password: 
Connection to 192.168.136.253 closed by remote host.
root@go-agent4:~# echo $?
255

```

**Comment by varac** [comment]
ok, i the pipeline is working now, but the behave tests are failing: https://github.com/pixelated/pixelated-platform/issues/154
