### ISSUE TITLE
docker 1.6.2 for wheezy doesn't provide initscript

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#149]
that's why the installation of pixelated-dispatcher-manager is failing atm in the platform build, see https://go.pixelated-project.org/go/tab/build/detail/pixelated-platform/1052/configure-leap_with_dispatcher/1/configure-leap_install_dispatcher

**Comment by cz8s** [comment]
we provide a initscript already.
But since the new docker, docker does not get registered as a service at the
initsystem. We do this now.  See
pixelated/puppet-pixelated@74dca2ebe00b6c743ac650a3ea8d195b15ddd205

**Comment by varac** [comment]
works again on latest staging
