### ISSUE TITLE
Review the platform installation process

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-platform#153]
## What
Some external contributors had problems to install and use the platform.
Because of that, we decided to review and make the installation process smoother.

## Definition of done
Someone outside the project can install platform without problems. 
(We can follow this process to make sure all it's ok)

- [x] Vagrant ssh login works
- [x] integration of pixelated into leap works

**Comment by cz8s** [comment]
I started on our documentation. First we need a working leap provider.
So I switched to follow the leap documentation at https://leap.se/en/docs/platform/tutorials/single-node-email
Since we want to use jessie, here are notes on what didn't work when using a jessie install.

* the 'Prepare your environment' paragraph should emphasize that the commands are run
on the laptop and not on the server

* we need to install our own leap tool:
```
mkdir -p ~/leap/example
git clone -b develop https://leap.se/git/leap_cli.git ~/leap/leap_cli
cd ~/leap/leap_cli
rake build
sudo rake install
````

* after ```leap new .``` we need to
```
cd ../leap_platform/
git checkout develop
git submodule update
cd -
```

* we have to use a ip from 10.5.5.0/24 to be able to install leap on a local vagrant box:
```
leap node add node1 ip_address:10.5.5.23 services:couchdb,mx,soledad,webapp
leap local start node1
```

**Comment by cz8s** [comment]
now we hit a bug with the jessie image of the vagrant box. It does not allow root access and
```leap init node1``` fails because it can't connect

**Comment by varac** [comment]
We should differentiate between users that want to have the platform up and running asap locally for playing, and users that want ro setup a remote test instance.

For the first case, i would recommend the [platform vagrant tutorial](https://leap.se/en/docs/platform/tutorials/vagrant)

The second use case is covered by the more extensive [Single node email tutorial](https://leap.se/en/docs/platform/tutorials/single-node-email)

**Comment by cz8s** [comment]
if we use the vagrant from leap_platform/Vagrantfile, it is quite easy to add pixelated.
We could make a script around that somehow. 
Problem is, that docker does not work with invalid domains.
We need to pass the hostname and ip to be added to /etc/hosts inside docker.

**Comment by cz8s** [comment]
okay. works for me. this are the steps:
```
git clone --branch develop --recursive git@github.com:leapcode/leap_platform.git
cd leap_platform
vagrant up
vagrant ssh -c 'cd /home/vagrant/leap/configuration/; mkdir -p files/puppet/modules'
vagrant ssh -c 'cd /home/vagrant/leap/configuration/; git submodule add https://github.com/pixelated/puppet-pixelated.git files/puppet/modules/pixelated'
vagrant ssh -c 'cd /home/vagrant/leap/configuration/; mkdir -p files/puppet/modules/custom/manifests'
vagrant ssh -c 'cd /home/vagrant/leap/configuration/; echo '{}' > services/pixelated.json'
vagrant ssh -c 'cd /home/vagrant/leap/configuration/; echo 'class custom { include ::pixelated::dispatcher }' > files/puppet/modules/custom/manifests/init.pp'
vagrant ssh -c "cd /home/vagrant/leap/configuration/; echo 'class custom { include ::pixelated::dispatcher }' > files/puppet/modules/custom/manifests/init.pp"
vagrant ssh -c "cd /home/vagrant/leap/configuration/; leap deploy"

**Comment by cz8s** [comment]
then we have to make the dispatcher accessible by the host machine:
```
vagrant halt
vboxmanage modifyvm 'jessie' --natpf1 "pixelated,tcp,,8081,,8080"
vagrant up
```

**Comment by cz8s** [comment]
The manual is now split in two parts: 'testing pixelated' and 'manual install'
I don't know if this solves our problem.
But everyone should be able to have something running very easily

**Comment by re-nobre** [comment]
Hey, @cz8s!
Today, Denis and Vitor wanted to install Pixelated on their machines. 
I suggested that they use the puppet readme for it.

They found some errors and created theses issues:

https://github.com/pixelated/puppet-pixelated/issues/1
https://github.com/pixelated/puppet-pixelated/issues/2
