### ISSUE TITLE
pixelated-server should use the right certificates

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#160]
after installing, pixelated-server is configured to use the apache snakeoil certs by default.
It should use the right LEAP certs in order to work properly:

```
root@dev1:~# cat /etc/default/pixelated-server 
HOME=/var/lib/pixelated
LEAP_PROVIDER=dev.pixelated-project.org
SSL_KEY=/etc/x509/keys/leap_commercial.key
SSL_CERT=/etc/x509/certs/leap_commercial.crt
LEAP_CA=/etc/ssl/certs/ca-certificates.crt

```

**Comment by cz8s** [comment]
the default is okay, but puppet should change the certificates if they are present

**Comment by varac** [comment]
done and deployed to unstable.bm

**Comment by fbernitt** [comment]
@varac Why did you reopen this issue?

**Comment by varac** [comment]
@fbernitt i dont know - probably by mistake.closing it again.
