### ISSUE TITLE
[leap] Test couchdb 2.0a

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#51]
we need to migrate from bigcouch to couchdb. see 
https://leap.se/code/issues/4886

**Comment by varac** [comment]
https://leap.se/code/issues/6187

**Comment by varac** [comment]
currently blocked by [Package couchdb from latest git](https://leap.se/code/issues/6187)

**Comment by re-nobre** [comment]
As we are testing migrate to couch 1.6, it doesn't make sense to focus on this now. 
So, I'm closing this issue and we can take a look again in this issue when couch 2.0 is released.
