### ISSUE TITLE
[leap] Research migration platform migration to Debian jessie

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#90]
upstream bug is https://leap.se/code/issues/6920

**Comment by varac** [comment]
mostly blocked by #91

**Comment by re-nobre** [comment]
This issue is too big, and we are not focusing on this migration to jessie now. 
When we decide to focus on this, we can create specific issues to achieve this goal.

**Comment by varac** [comment]
After the main blocker (bigcouch) was removed, we can now start evaluating what further blocks us from upgrading to jessie.

Here's the an probably uncomplete list what comes to my mind:

- Puppet modules: Most work will be due to the new major version bump of puppet from 2 to 3. Different puppet module needs to be updated, but from what i can see now it's just minor fixes. We are mostly using the [shared-modules-group modules](https://gitlab.com/shared-puppet-modules-group), which has mapped [all issues needed to get fixed for puppet 3](link follows)

**Comment by varac** [comment]
see related issue #130
